### PR TITLE
Adding support for Enter key on MacOS and closing #167

### LINKED ISSUE #167: Duplicate key entires?
I was curious about this when I added fa2b880 - are the lines below duplicated for a reason?

https://github.com/nut-tree/libnut-core/blob/fa2b880a7742cd9fa3656553aa44c523bd3809fb/src/main.cc#L303-L307
https://github.com/nut-tree/libnut-core/blob/fa2b880a7742cd9fa3656553aa44c523bd3809fb/src/main.cc#L309-L313

### PR DESCRIPTION
**Pull request by smithkyle**
adds support for numpad Enter key on macos, differentiates between return/enter keys, and removes duplicate lines closes #167

### CODE REVIEW

**Comment by smithkyle** [comment]
I've been searching high and low for keycodes for Windows and X11 - just about everything I've seen says that they don't differentiate between return and enter on the keypad...however, I just now came across a possible keycode for X11: `XK_KP_Enter` per [this site](https://www.cl.cam.ac.uk/~mgk25/ucs/keysymdef.h). I'm not sure if that is correct though - I know you had found an additional keycode for my last PR, so I'm not sure what you use as your source for keycodes.

**Comment by smithkyle** [comment]
Also, how would I test this locally? I know that I can use `npm link` to pull the local `libnut` package in to my local nut.js repo, but what about the `libnut-{platform}` packages? Would I run the build scripts to generate those packages and then `npm link` them into my local nut.js repo?

**Comment by s1hofmann** [comment]
@smithkyle The platform dependent packages of libnut make it a bit hard, since they are generated via CI. The easiest way for now would be to do an `npm install` in your nut.js repo, then replace the platform specific binary you built on your machine in your respective `node_modules` folder

**Comment by smithkyle** [comment]
👍🏻 that's exactly what did 😀 let me know about the x11 enter keycode

**Comment by smithkyle** [comment]
Hello! Hope you're doing well. I know you've been busy - just wanted to bump this up.

**Pull request merged**
